In [7]:
import numpy as np
ans=3
EE=np.load('Data/9_5Error_all.npy')

In [9]:
print(np.argmin(np.average(EE,axis=1)))
print(np.argsort(np.average(EE,axis=1)))
print(np.average(EE,axis=1)[ans]/np.average(EE,axis=1).mean())
N=np.zeros(5)
for i in range (0,5):
    N[i]=np.argmin(EE[:,i])
print(N)

6
[6 2 1 5 3 0 4 7]
1.0418351550845903
[6. 1. 6. 2. 6.]


In [10]:
np.load('Data/9_5Termination_all.npy')

array(1)

In [11]:
import numpy as np
ans=4
EE=np.load('Data/9_6Error_all.npy')

In [12]:
print(np.argmin(np.average(EE,axis=1)))
print(np.argsort(np.average(EE,axis=1)))
print(np.average(EE,axis=1)[ans]/np.average(EE,axis=1).mean())
N=np.zeros(5)
for i in range (0,5):
    N[i]=np.argmin(EE[:,i])
print(N)

2
[2 6 1 0 5 4 3 7]
1.0464062527137925
[2. 1. 6. 6. 6.]


In [13]:
np.load('Data/9_6Termination_all.npy')

array(3)

In [14]:
np.load('Data/9_4cTermination_all.npy')

array(2)

In [16]:
import numpy as np
ans=3
EE=np.load('Data/9_5Error_all.npy')
print(np.argmin(np.average(EE,axis=1)))
print(np.argsort(np.average(EE,axis=1)))
print(np.average(EE,axis=1)[ans]/np.average(EE,axis=1).mean())
N=np.zeros(5)
for i in range (0,5):
    N[i]=np.argmin(EE[:,i])
print(N)

6
[6 2 1 5 3 0 4 7]
1.0418351550845903
[6. 1. 6. 2. 6.]


In [17]:
np.load('Data/9_5_rerun_allTermination_all.npy')

array(4)

In [12]:
import numpy as np
ans=1
E=np.load('Data/9_0Error_no_rotation_rerun_v.npy')
print(np.argmin(np.average(E,axis=1)))
print(np.argsort(np.average(E,axis=1)))
print(np.average(E,axis=1)[ans]/np.average(E,axis=1).mean())
N=np.zeros(5)
for i in range (0,5):
    N[i]=np.argmin(E[:,i])
print(N)
E1=np.load('Data/9_0Error_no_rotation_rerun.npy')
print(np.argmin(np.average(E1,axis=1)))
print(np.argsort(np.average(E1,axis=1)))
print(np.average(E1,axis=1)[ans]/np.average(E1,axis=1).mean())
NNN=np.zeros(5)
for i in range (0,5):
    NNN[i]=np.argmin(E1[:,i])
print(NNN)
print(np.argmin(np.average(E+E1,axis=1)))
print(np.argsort(np.average(E+E1,axis=1)))
print(np.average(E+E1,axis=1)[ans]/np.average(E+E1,axis=1).mean())
NN=np.zeros(5)
for i in range (0,5):
    NN[i]=np.argmin(E[:,i]+E1[:,i])
print(NN)

0
[0 7 4 1 2 6 5 3]
1.017891270207472
[0. 0. 7. 0. 7.]
0
[0 7 4 5 1 6 2 3]
1.0430718851938352
[7. 7. 0. 0. 0.]
0
[0 7 4 1 2 6 5 3]
1.0304066371078628
[0. 0. 7. 0. 7.]


In [13]:
import numpy as np
ans=1
E=np.load('Data/9_1Error_no_rotation_rerun_v.npy')
print(np.argmin(np.average(E,axis=1)))
print(np.argsort(np.average(E,axis=1)))
print(np.average(E,axis=1)[ans]/np.average(E,axis=1).mean())
N=np.zeros(5)
for i in range (0,5):
    N[i]=np.argmin(E[:,i])
print(N)
E1=np.load('Data/9_1Error_no_rotation_rerun.npy')
print(np.argmin(np.average(E1,axis=1)))
print(np.argsort(np.average(E1,axis=1)))
print(np.average(E1,axis=1)[ans]/np.average(E1,axis=1).mean())
NNN=np.zeros(5)
for i in range (0,5):
    NNN[i]=np.argmin(E1[:,i])
print(NNN)
print(np.argmin(np.average(E+E1,axis=1)))
print(np.argsort(np.average(E+E1,axis=1)))
print(np.average(E+E1,axis=1)[ans]/np.average(E+E1,axis=1).mean())
NN=np.zeros(5)
for i in range (0,5):
    NN[i]=np.argmin(E[:,i]+E1[:,i])
print(NN)
print(np.load('Data/9_1Termination_no_rotation_rerun_v.npy'))
print(np.load('Data/9_1Termination_no_rotation_rerun.npy'))

1
[1 2 7 6 4 3 5 0]
0.8628159939615656
[1. 1. 1. 1. 1.]
1
[1 2 7 3 6 4 5 0]
0.8558310415488913
[1. 1. 1. 1. 1.]
1
[1 2 7 6 3 4 5 0]
0.8594982953768605
[1. 1. 1. 1. 1.]
1
2


In [9]:
print(np.load('Data/9_0Termination_no_rotation_rerun_v.npy'))
print(np.load('Data/9_0Termination_no_rotation_rerun.npy'))

3
2


In [15]:
import numpy as np
ans=2
E=np.load('Data/9_2Error_no_rotation_rerun_v.npy')
print(np.argmin(np.average(E,axis=1)))
print(np.argsort(np.average(E,axis=1)))
print(np.average(E,axis=1)[ans]/np.average(E,axis=1).mean())
N=np.zeros(5)
for i in range (0,5):
    N[i]=np.argmin(E[:,i])
print(N)
E1=np.load('Data/9_2Error_no_rotation_rerun.npy')
print(np.argmin(np.average(E1,axis=1)))
print(np.argsort(np.average(E1,axis=1)))
print(np.average(E1,axis=1)[ans]/np.average(E1,axis=1).mean())
NNN=np.zeros(5)
for i in range (0,5):
    NNN[i]=np.argmin(E1[:,i])
print(NNN)
print(np.argmin(np.average(E+E1,axis=1)))
print(np.argsort(np.average(E+E1,axis=1)))
print(np.average(E+E1,axis=1)[ans]/np.average(E+E1,axis=1).mean())
NN=np.zeros(5)
for i in range (0,5):
    NN[i]=np.argmin(E[:,i]+E1[:,i])
print(NN)
print(np.load('Data/9_2Termination_no_rotation_rerun_v.npy'))
print(np.load('Data/9_2Termination_no_rotation_rerun.npy'))

6
[6 2 1 4 0 3 5 7]
0.9358371604812917
[2. 6. 1. 2. 6.]
6
[6 2 1 4 5 0 7 3]
0.9119564707253639
[6. 6. 1. 2. 2.]
6
[6 2 1 4 5 0 3 7]
0.9228640610847958
[6. 6. 1. 2. 2.]
1
4


In [20]:
import numpy as np
ans=4
E=np.load('Data/9_6Error_no_rotation_rerun_v.npy')
print(np.argmin(np.average(E,axis=1)))
print(np.argsort(np.average(E,axis=1)))
print(np.average(E,axis=1)[ans]/np.average(E,axis=1).mean())
N=np.zeros(5)
for i in range (0,5):
    N[i]=np.argmin(E[:,i])
print(N)
E1=np.load('Data/9_6Error_no_rotation_rerun.npy')
print(np.argmin(np.average(E1,axis=1)))
print(np.argsort(np.average(E1,axis=1)))
print(np.average(E1,axis=1)[ans]/np.average(E1,axis=1).mean())
NNN=np.zeros(5)
for i in range (0,5):
    NNN[i]=np.argmin(E1[:,i])
print(NNN)
print(np.argmin(np.average(E+E1,axis=1)))
print(np.argsort(np.average(E+E1,axis=1)))
print(np.average(E+E1,axis=1)[ans]/np.average(E+E1,axis=1).mean())
NN=np.zeros(5)
for i in range (0,5):
    NN[i]=np.argmin(E[:,i]+E1[:,i])
print(NN)
print(np.load('Data/9_6Termination_no_rotation_rerun_v.npy'))
print(np.load('Data/9_6Termination_no_rotation_rerun.npy'))

7
[7 1 3 4 2 6 0 5]
1.000033645789151
[1. 3. 7. 7. 7.]
7
[7 1 3 6 2 4 0 5]
1.080333137057423
[1. 7. 1. 7. 7.]
7
[7 1 3 4 6 2 0 5]
1.0372037311032274
[1. 1. 7. 7. 7.]
3
3


In [22]:
import numpy as np
ans=0
E=np.load('Data/9_7Error_no_rotation_rerun_v.npy')
print(np.argmin(np.average(E,axis=1)))
print(np.argsort(np.average(E,axis=1)))
print(np.average(E,axis=1)[ans]/np.average(E,axis=1).mean())
N=np.zeros(5)
for i in range (0,5):
    N[i]=np.argmin(E[:,i])
print(N)
E1=np.load('Data/9_7Error_no_rotation_rerun.npy')
print(np.argmin(np.average(E1,axis=1)))
print(np.argsort(np.average(E1,axis=1)))
print(np.average(E1,axis=1)[ans]/np.average(E1,axis=1).mean())
NNN=np.zeros(5)
for i in range (0,5):
    NNN[i]=np.argmin(E1[:,i])
print(NNN)
print(np.argmin(np.average(E+E1,axis=1)))
print(np.argsort(np.average(E+E1,axis=1)))
print(np.average(E+E1,axis=1)[ans]/np.average(E+E1,axis=1).mean())
NN=np.zeros(5)
for i in range (0,5):
    NN[i]=np.argmin(E[:,i]+E1[:,i])
print(NN)
print(np.load('Data/9_7Termination_no_rotation_rerun_v.npy'))
print(np.load('Data/9_7Termination_no_rotation_rerun.npy'))

1
[1 0 6 3 7 5 4 2]
0.9291713341952172
[1. 1. 0. 1. 1.]
1
[1 0 6 7 3 5 4 2]
0.9255287778534093
[1. 1. 4. 1. 1.]
1
[1 0 6 3 7 5 4 2]
0.9275738198645088
[1. 1. 1. 1. 1.]
2
3


In [23]:
import numpy as np
ans=6
E=np.load('Data/9_8Error_no_rotation_rerun_v.npy')
print(np.argmin(np.average(E,axis=1)))
print(np.argsort(np.average(E,axis=1)))
print(np.average(E,axis=1)[ans]/np.average(E,axis=1).mean())
N=np.zeros(5)
for i in range (0,5):
    N[i]=np.argmin(E[:,i])
print(N)
E1=np.load('Data/9_8Error_no_rotation_rerun.npy')
print(np.argmin(np.average(E1,axis=1)))
print(np.argsort(np.average(E1,axis=1)))
print(np.average(E1,axis=1)[ans]/np.average(E1,axis=1).mean())
NNN=np.zeros(5)
for i in range (0,5):
    NNN[i]=np.argmin(E1[:,i])
print(NNN)
print(np.argmin(np.average(E+E1,axis=1)))
print(np.argsort(np.average(E+E1,axis=1)))
print(np.average(E+E1,axis=1)[ans]/np.average(E+E1,axis=1).mean())
NN=np.zeros(5)
for i in range (0,5):
    NN[i]=np.argmin(E[:,i]+E1[:,i])
print(NN)
print(np.load('Data/9_8Termination_no_rotation_rerun_v.npy'))
print(np.load('Data/9_8Termination_no_rotation_rerun.npy'))

FileNotFoundError: [Errno 2] No such file or directory: 'Data/9_8Error_no_rotation_rerun_v.npy'

In [31]:
NN='9_35'
ans=4
import numpy as np
EE=np.load('Data/'+str(NN)+'Error_no_rotation_rerun.npy')
T=np.load('Data/'+str(NN)+'Termination_no_rotation_rerun.npy')

In [32]:

    N=np.zeros(5)
    for i in range (0,5):
        N[i]=np.argmin(EE[:,i])
    print(np.argmin(np.average(EE,axis=1)))
    print(np.argsort(np.average(EE,axis=1)))
    print(np.average(EE,axis=1)[ans]/np.average(EE,axis=1).mean())
    print(N)
    print(T)

6
[6 1 3 4 2 7 0 5]
1.0190908292625263
[6. 6. 6. 6. 1.]
3
