In [2]:
import pandas as pd
data=pd.read_csv('/afs/inf.ed.ac.uk/user/s18/s1883226/Downloads/questions.csv' )

In [24]:
import numpy as np
data=data.fillna(0)
np.save('data.npy',data)

In [17]:
data.head(5)

question  Unnamed: 1  size1  size2  size3  shape1  shape2  shape3  \
0       1.0         1.0    1.0    0.0    0.0     1.0     0.0     0.0   
1       1.0         2.0    1.0    0.0    0.0     1.0     0.0     0.0   
2       1.0         3.0    1.0    0.0    0.0     1.0     0.0     0.0   
3       1.0         4.0    1.0    2.0    0.0     2.0     0.0     0.0   
4       1.0         5.0    1.0    2.0    0.0     2.0     0.0     0.0   

   shape_other  position1  position2  position3  position_y_1  position_y_2  \
0          0.0        1.0        0.0        0.0           1.0           0.0   
1          0.0        1.0        0.0        0.0           1.0           0.0   
2          0.0        1.0        0.0        0.0           1.0           0.0   
3          0.0        2.0        0.0        0.0           1.0           0.0   
4          0.0        2.0        0.0        0.0           1.0           0.0   

   position_y_3  
0           0.0  
1           0.0  
2           0.0  
3           0.0  
4           0.0

In [18]:
data.shape

(576, 15)

In [41]:
data=np.load('data.npy')
q=data[data[:,0]==1]
q=q[:,2:]
q[0,:]

array([1., 0., 0., 1., 0., 0., 0., 1., 0., 0., 1., 0., 0.])

In [23]:
data.iloc[0:16]

question  Unnamed: 1  size1  size2  size3  shape1  shape2  shape3  \
0        1.0         1.0    1.0    0.0    0.0     1.0     0.0     0.0   
1        1.0         2.0    1.0    0.0    0.0     1.0     0.0     0.0   
2        1.0         3.0    1.0    0.0    0.0     1.0     0.0     0.0   
3        1.0         4.0    1.0    2.0    0.0     2.0     0.0     0.0   
4        1.0         5.0    1.0    2.0    0.0     2.0     0.0     0.0   
5        1.0         6.0    1.0    2.0    0.0     2.0     0.0     0.0   
6        1.0         7.0    1.0    2.0    3.0     3.0     0.0     0.0   
7        1.0         8.0    1.0    2.0    3.0     3.0     0.0     0.0   
8        1.0         9.0    0.0    2.5    3.0     2.0     0.0     0.0   
9        1.0        10.0    1.0    2.0    3.0     5.0     0.0     0.0   
10       1.0        11.0    1.0    2.0    0.0     2.0     0.0     0.0   
11       1.0        12.0    1.0    0.0    0.0     1.0     0.0     0.0   
12       1.0        13.0    1.0    0.0    3.0     2.0     0.0     0.0   
13       1.0        14.0    0.0    0.0    3.0     1.0     0.0     0.0   
14       1.0        15.0    0.0    2.0    0.0     1.0     0.0     0.0   
15       1.0        16.0    1.0    2.0    3.0     3.0     0.0     0.0   

    shape_other  position1  position2  position3  position_y_1  position_y_2  \
0           0.0        1.0        0.0        0.0           1.0           0.0   
1           0.0        1.0        0.0        0.0           1.0           0.0   
2           0.0        1.0        0.0        0.0           1.0           0.0   
3           0.0        2.0        0.0        0.0           1.0           0.0   
4           0.0        2.0        0.0        0.0           1.0           0.0   
5           0.0        2.0        0.0        0.0           1.0           0.0   
6           0.0        3.0        0.0        0.0           1.0           0.0   
7           0.0        3.0        0.0        0.0           1.0           0.0   
8           0.0        2.0        0.0        0.0           1.0           0.0   
9           0.0        5.0        0.0        0.0           1.0           0.0   
10          0.0        2.0        0.0        0.0           1.0           0.0   
11          0.0        1.0        0.0        0.0           1.0           0.0   
12          0.0        2.0        0.0        0.0           1.0           0.0   
13          0.0        1.0        0.0        0.0           1.0           0.0   
14          0.0        1.0        0.0        0.0           1.0           0.0   
15          0.0        3.0        0.0        0.0           1.0           0.0   

    position_y_3  
0            0.0  
1            0.0  
2            0.0  
3            0.0  
4            0.0  
5            0.0  
6            0.0  
7            0.0  
8            0.0  
9            0.0  
10           0.0  
11           0.0  
12           0.0  
13           0.0  
14           0.0  
15           0.0

In [44]:
import random
np.random.randint(2,size=13)

array([0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1])

In [1]:
from gen_r import gen_r

In [3]:
t,a=gen_r(1)

In [6]:
t.shape

(128, 13)

In [7]:
a.shape

(128, 7)

In [9]:
5%2

1

In [25]:
from gen_r import gen_r_test

In [26]:
gen_r_test(1,1)

(array([[-1. ,  0.5,  0. , -1. ,  0. ,  0. ,  0. , -1. ,  0. ,  0. ,  0. ,
          0. ,  0. ],
        [-1. ,  0.5,  0. , -1. ,  0. ,  0. ,  0. , -1. ,  0. ,  0. ,  0. ,
          0. ,  0. ],
        [ 0. ,  0. ,  0. ,  2. ,  0. ,  0. ,  0. ,  2. ,  0. ,  0. ,  0. ,
          0. ,  0. ],
        [ 0. ,  0. ,  0. ,  2. ,  0. ,  0. ,  0. ,  2. ,  0. ,  0. ,  0. ,
          0. ,  0. ],
        [ 0. ,  0. , -3. , -1. ,  0. ,  0. ,  0. , -1. ,  0. ,  0. ,  0. ,
          0. ,  0. ],
        [ 0. ,  0. , -3. , -1. ,  0. ,  0. ,  0. , -1. ,  0. ,  0. ,  0. ,
          0. ,  0. ],
        [ 0. , -2. , -3. , -2. ,  0. ,  0. ,  0. , -2. ,  0. ,  0. ,  0. ,
          0. ,  0. ],
        [ 0. , -2. , -3. , -2. ,  0. ,  0. ,  0. , -2. ,  0. ,  0. ,  0. ,
          0. ,  0. ],
        [ 0. , -2. ,  0. , -1. ,  0. ,  0. ,  0. , -1. ,  0. ,  0. ,  0. ,
          0. ,  0. ],
        [ 0. , -2. ,  0. , -1. ,  0. ,  0. ,  0. , -1. ,  0. ,  0. ,  0. ,
          0. ,  0. ],
        [-1. , -2. ,  0. , -2.

In [17]:
from gen_r import gen_r_ref

In [23]:
t,a=gen_r_ref(1)
t[t!=0].shape[0]>0

False

In [1]:
from fcon_rep import train_fcon

In [2]:
train_fcon(2,1)

W0730 19:34:55.424888 139944149321536 deprecation_wrapper.py:119] From /afs/inf.ed.ac.uk/user/s18/s1883226/Downloads/experiment/Untitled Folder/fcon_rep.py:29: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

W0730 19:34:55.445516 139944149321536 deprecation_wrapper.py:119] From /afs/inf.ed.ac.uk/user/s18/s1883226/Downloads/experiment/Untitled Folder/fcon_rep.py:34: The name tf.random_normal is deprecated. Please use tf.random.normal instead.

W0730 19:34:55.473867 139944149321536 deprecation.py:506] From /afs/inf.ed.ac.uk/user/s18/s1883226/Downloads/experiment/Untitled Folder/fcon_rep.py:11: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
W0730 19:34:55.487723 139944149321536 deprecation.py:323] From /afs/inf.ed.ac.uk/user/s18/s1883226/Downloads/experiment/Untitle

Step 1, Minibatch Loss= 60.9584, Train Accuracy= 0.086
Step 2, Minibatch Loss= 53.7653, Train Accuracy= 0.172
Step 3, Minibatch Loss= 59.3163, Train Accuracy= 0.078
Step 4, Minibatch Loss= 53.5966, Train Accuracy= 0.156
Step 5, Minibatch Loss= 56.5039, Train Accuracy= 0.141
Step 6, Minibatch Loss= 44.7340, Train Accuracy= 0.203
Step 7, Minibatch Loss= 51.6570, Train Accuracy= 0.086
Step 8, Minibatch Loss= 54.7764, Train Accuracy= 0.141
Step 9, Minibatch Loss= 51.8812, Train Accuracy= 0.109
Step 10, Minibatch Loss= 42.2508, Train Accuracy= 0.117
Step 11, Minibatch Loss= 51.0835, Train Accuracy= 0.133
Step 12, Minibatch Loss= 51.4897, Train Accuracy= 0.133
Step 13, Minibatch Loss= 37.0440, Train Accuracy= 0.133
Step 14, Minibatch Loss= 39.9110, Train Accuracy= 0.125
Step 15, Minibatch Loss= 41.3103, Train Accuracy= 0.141
Step 16, Minibatch Loss= 38.3279, Train Accuracy= 0.117
Step 17, Minibatch Loss= 40.3058, Train Accuracy= 0.117
Step 18, Minibatch Loss= 37.0739, Train Accuracy= 0.070
S

Step 156, Minibatch Loss= 1.4911, Train Accuracy= 0.227
Step 157, Minibatch Loss= 1.5879, Train Accuracy= 0.242
Step 158, Minibatch Loss= 1.4332, Train Accuracy= 0.305
Step 159, Minibatch Loss= 1.3679, Train Accuracy= 0.328
Step 160, Minibatch Loss= 1.6098, Train Accuracy= 0.188
Step 161, Minibatch Loss= 1.6433, Train Accuracy= 0.219
Step 162, Minibatch Loss= 1.4079, Train Accuracy= 0.266
Step 163, Minibatch Loss= 1.5147, Train Accuracy= 0.297
Step 164, Minibatch Loss= 1.3680, Train Accuracy= 0.234
Step 165, Minibatch Loss= 1.7363, Train Accuracy= 0.266
Step 166, Minibatch Loss= 1.4201, Train Accuracy= 0.250
Step 167, Minibatch Loss= 1.4099, Train Accuracy= 0.289
Step 168, Minibatch Loss= 1.4383, Train Accuracy= 0.273
Step 169, Minibatch Loss= 1.4147, Train Accuracy= 0.250
Step 170, Minibatch Loss= 1.6281, Train Accuracy= 0.305
Step 171, Minibatch Loss= 1.5053, Train Accuracy= 0.273
Step 172, Minibatch Loss= 1.7548, Train Accuracy= 0.180
Step 173, Minibatch Loss= 1.6914, Train Accuracy

Step 315, Minibatch Loss= 1.4103, Train Accuracy= 0.250
Step 316, Minibatch Loss= 1.6154, Train Accuracy= 0.219
Step 317, Minibatch Loss= 1.4802, Train Accuracy= 0.250
Step 318, Minibatch Loss= 1.3848, Train Accuracy= 0.250
Step 319, Minibatch Loss= 1.4290, Train Accuracy= 0.273
Step 320, Minibatch Loss= 1.4671, Train Accuracy= 0.250
Step 321, Minibatch Loss= 1.5671, Train Accuracy= 0.227
Step 322, Minibatch Loss= 1.7234, Train Accuracy= 0.188
Step 323, Minibatch Loss= 1.2450, Train Accuracy= 0.391
Step 324, Minibatch Loss= 1.6010, Train Accuracy= 0.211
Step 325, Minibatch Loss= 1.6844, Train Accuracy= 0.266
Step 326, Minibatch Loss= 1.4202, Train Accuracy= 0.336
Step 327, Minibatch Loss= 1.5691, Train Accuracy= 0.273
Step 328, Minibatch Loss= 1.7849, Train Accuracy= 0.203
Step 329, Minibatch Loss= 1.6535, Train Accuracy= 0.281
Step 330, Minibatch Loss= 1.6664, Train Accuracy= 0.273
Step 331, Minibatch Loss= 1.7514, Train Accuracy= 0.266
Step 332, Minibatch Loss= 2.0625, Train Accuracy

Step 464, Minibatch Loss= 1.3916, Train Accuracy= 0.281
Step 465, Minibatch Loss= 1.7268, Train Accuracy= 0.266
Step 466, Minibatch Loss= 1.6223, Train Accuracy= 0.219
Step 467, Minibatch Loss= 1.5525, Train Accuracy= 0.242
Step 468, Minibatch Loss= 1.8523, Train Accuracy= 0.234
Step 469, Minibatch Loss= 1.5246, Train Accuracy= 0.281
Step 470, Minibatch Loss= 1.6160, Train Accuracy= 0.266
Step 471, Minibatch Loss= 1.6019, Train Accuracy= 0.227
Step 472, Minibatch Loss= 1.3629, Train Accuracy= 0.250
Step 473, Minibatch Loss= 1.3064, Train Accuracy= 0.258
Step 474, Minibatch Loss= 1.3653, Train Accuracy= 0.297
Step 475, Minibatch Loss= 1.4051, Train Accuracy= 0.273
Step 476, Minibatch Loss= 1.5149, Train Accuracy= 0.203
Step 477, Minibatch Loss= 1.5244, Train Accuracy= 0.305
Step 478, Minibatch Loss= 1.4469, Train Accuracy= 0.289
Step 479, Minibatch Loss= 1.7579, Train Accuracy= 0.227
Step 480, Minibatch Loss= 1.5721, Train Accuracy= 0.289
Step 481, Minibatch Loss= 1.6620, Train Accuracy

(array([1561.84964998,    0.        ,  821.25884779,  622.57299223,
         985.98966653,  727.96294416, 1192.44169218,  985.98966653]),
 array([1649.30494919,    0.        ,  897.26954963,  630.50182213,
        1059.24977041,  756.26498041, 1278.12210479, 1059.24977041]),
 array([1591.00141638,    0.        ,  846.5957484 ,  625.21593553,
        1010.40970116,  737.39695624, 1221.00182972, 1010.40970116]),
 0)

In [1]:
from run_f_rep import run_f_ref

In [2]:
run_f_ref(1,7)

W0730 21:00:42.958361 140554664703808 deprecation_wrapper.py:119] From /afs/inf.ed.ac.uk/user/s18/s1883226/Downloads/experiment/Untitled Folder/fcon_rep.py:29: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

W0730 21:00:43.008900 140554664703808 deprecation_wrapper.py:119] From /afs/inf.ed.ac.uk/user/s18/s1883226/Downloads/experiment/Untitled Folder/fcon_rep.py:34: The name tf.random_normal is deprecated. Please use tf.random.normal instead.

W0730 21:00:43.101291 140554664703808 deprecation.py:506] From /afs/inf.ed.ac.uk/user/s18/s1883226/Downloads/experiment/Untitled Folder/fcon_rep.py:11: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
W0730 21:00:43.149108 140554664703808 deprecation.py:323] From /afs/inf.ed.ac.uk/user/s18/s1883226/Downloads/experiment/Untitle

In [10]:
i=1
ans=7
import numpy as np
EEE1=np.load('Data/'+str(i)+'_EEE1.npy')
EEE2=np.load('Data/'+str(i)+'_EEE2.npy')
EEE=np.load('Data/'+str(i)+'_EEE.npy')
Num=np.load('Data/'+str(i)+'_Numm.npy')
print(np.argmin(np.average(EEE1,axis=1)))
n=np.zeros(50)
for i in range (0,50):
    n[i]=np.argmin(EEE1[:,i])
print(np.where(n==ans)[0].size)
print(np.argsort(np.average(EEE,axis=1)))
n=np.zeros(50)
for i in range (0,50):
    n[i]=np.argsort(EEE[:,i])
print(np.where(n==ans)[0].size)
print(np.average(EEE,axis=1)[ans]/EEE.mean())

7
50
7
50
0.0


In [66]:
i=21
ans=0
import numpy as np
EEE1=np.load('Data/'+str(i)+'_EEE1.npy')
EEE2=np.load('Data/'+str(i)+'_EEE2.npy')
EEE=np.load('Data/'+str(i)+'_EEE.npy')
Num=np.load('Data/'+str(i)+'_Numm.npy')
print(np.argsort(np.average(EEE1,axis=1)))
n=np.zeros(50)
for i in range (0,50):
    n[i]=np.argmin(EEE1[:,i])
print(np.where(n==ans)[0].size)
print(np.argsort(np.average(EEE,axis=1)))
n=np.zeros(50)
for i in range (0,50):
    n[i]=np.argmin(EEE[:,i])
print(np.where(n==ans)[0].size)
print(np.average(EEE1,axis=1)[ans]/EEE1.mean())
print(np.average(EEE,axis=1)[ans]/EEE.mean())


[7 5 1 2 4 3 6 0]
0
[7 5 1 3 4 2 6 0]
0
1.0632602692407285
1.12067711982897


In [59]:
i=14
ans=3
import numpy as np
EEE1=np.load('Data/'+str(i)+'_EEE1.npy')
EEE2=np.load('Data/'+str(i)+'_EEE2.npy')
EEE=np.load('Data/'+str(i)+'_EEE.npy')
Num=np.load('Data/'+str(i)+'_Numm.npy')
print(np.argsort(np.average(EEE2,axis=1)))
n=np.zeros(50)
for i in range (0,50):
    n[i]=np.argmin(EEE2[:,i])
print(np.where(n==ans)[0].size)


[7 1 3 2 5 6 0 4]
1


In [4]:
n=np.zeros(50)
for i in range (0,50):
    n[i]=np.argmin(EEE1[:,i])
np.where(n==ans)[0].size

50

In [6]:
EEE

array([[ 436.21482934,  432.49493383,    0.        ,    0.        ,
           0.        ,    0.        ,    0.        ,    0.        ,
           0.        ,    0.        ,    0.        ,    0.        ,
           0.        ,    0.        ,    0.        ,    0.        ,
           0.        ,    0.        ,    0.        ,    0.        ,
           0.        ,    0.        ,    0.        ,    0.        ,
           0.        ,    0.        ,    0.        ,    0.        ,
           0.        ,    0.        ,    0.        ,    0.        ,
           0.        ,    0.        ,    0.        ,    0.        ,
           0.        ,    0.        ,    0.        ,    0.        ,
           0.        ,    0.        ,    0.        ,    0.        ,
           0.        ,    0.        ,    0.        ,    0.        ,
           0.        ,    0.        ],
       [ 521.78145401,  506.91328659,    0.        ,    0.        ,
           0.        ,    0.        ,    0.        ,    0.        ,
         