In [1]:
from foward_error_ex1 import foward_error

In [2]:
foward_error(9,[0,1,2,5,6,7],2,'9_c_3')

W0717 15:42:56.856616 140576563742528 deprecation_wrapper.py:119] From /afs/inf.ed.ac.uk/user/s18/s1883226/Downloads/experiment/twobyt/con1.py:21: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

W0717 15:42:56.873991 140576563742528 deprecation_wrapper.py:119] From /afs/inf.ed.ac.uk/user/s18/s1883226/Downloads/experiment/twobyt/con1.py:27: The name tf.random_normal is deprecated. Please use tf.random.normal instead.

W0717 15:42:56.923740 140576563742528 deprecation_wrapper.py:119] From /afs/inf.ed.ac.uk/user/s18/s1883226/Downloads/experiment/twobyt/convo.py:11: The name tf.nn.max_pool is deprecated. Please use tf.nn.max_pool2d instead.

W0717 15:42:56.931131 140576563742528 deprecation.py:506] From /afs/inf.ed.ac.uk/user/s18/s1883226/Downloads/experiment/twobyt/convo.py:38: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of

Step 1, Minibatch Loss= 21339.4473, Train Accuracy= 0.000
Step 2, Minibatch Loss= 16407.2129, Train Accuracy= 0.000
Step 3, Minibatch Loss= 12248.8105, Train Accuracy= 0.000
Step 4, Minibatch Loss= 8158.5859, Train Accuracy= 0.000
Step 5, Minibatch Loss= 11024.0020, Train Accuracy= 0.000
Step 6, Minibatch Loss= 2862.5542, Train Accuracy= 0.000
Step 7, Minibatch Loss= 5946.2324, Train Accuracy= 0.000
Step 8, Minibatch Loss= 984.8907, Train Accuracy= 0.000
Step 9, Minibatch Loss= 3700.1021, Train Accuracy= 0.000
Step 10, Minibatch Loss= 563.7710, Train Accuracy= 0.000
Step 11, Minibatch Loss= 0.0000, Train Accuracy= 1.000
Step 1, Minibatch Loss= 26.7966, Train Accuracy= 0.750
Step 2, Minibatch Loss= 14.2766, Train Accuracy= 0.625
Step 3, Minibatch Loss= 0.0000, Train Accuracy= 1.000
Step 4, Minibatch Loss= 0.0000, Train Accuracy= 1.000
Step 5, Minibatch Loss= 0.0000, Train Accuracy= 1.000
Step 6, Minibatch Loss= 0.0000, Train Accuracy= 1.000
Step 1, Minibatch Loss= 2202.7100, Train Accur

In [5]:
import numpy as np
a=np.zeros((8,1024))
b=np.zeros((8,49*2*3))
np.hstack((a,b))

(8, 1318)

In [1]:
from foward_error_ex2 import foward_error
foward_error(9,[0,1,2,5,6,7],2,'9_c_3')

W0718 11:39:58.974272 140608613193536 deprecation_wrapper.py:119] From /afs/inf.ed.ac.uk/user/s18/s1883226/Downloads/experiment/twobyt/con1.py:21: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

W0718 11:39:58.992835 140608613193536 deprecation_wrapper.py:119] From /afs/inf.ed.ac.uk/user/s18/s1883226/Downloads/experiment/twobyt/con1.py:27: The name tf.random_normal is deprecated. Please use tf.random.normal instead.

W0718 11:39:59.042061 140608613193536 deprecation_wrapper.py:119] From /afs/inf.ed.ac.uk/user/s18/s1883226/Downloads/experiment/twobyt/convo.py:11: The name tf.nn.max_pool is deprecated. Please use tf.nn.max_pool2d instead.

W0718 11:39:59.050083 140608613193536 deprecation.py:506] From /afs/inf.ed.ac.uk/user/s18/s1883226/Downloads/experiment/twobyt/convo.py:38: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of

Step 1, Minibatch Loss= 0.0000, Train Accuracy= 1.000
Step 2, Minibatch Loss= 42361.6953, Train Accuracy= 0.000
Step 3, Minibatch Loss= 27541.4473, Train Accuracy= 0.000
Step 4, Minibatch Loss= 15018.6523, Train Accuracy= 0.000
Step 5, Minibatch Loss= 24377.7949, Train Accuracy= 0.000
Step 6, Minibatch Loss= 5723.6992, Train Accuracy= 0.000
Step 7, Minibatch Loss= 13929.2480, Train Accuracy= 0.000
Step 8, Minibatch Loss= 0.0000, Train Accuracy= 1.000
Step 1, Minibatch Loss= 549.7932, Train Accuracy= 0.625
Step 2, Minibatch Loss= 844.1377, Train Accuracy= 0.375
Step 3, Minibatch Loss= 464.1946, Train Accuracy= 0.625
Step 4, Minibatch Loss= 562.1034, Train Accuracy= 0.500
Step 5, Minibatch Loss= 505.2040, Train Accuracy= 0.500
Step 6, Minibatch Loss= 559.9073, Train Accuracy= 0.375
Step 7, Minibatch Loss= 392.7526, Train Accuracy= 0.500
Step 8, Minibatch Loss= 420.7573, Train Accuracy= 0.375
Step 9, Minibatch Loss= 350.3333, Train Accuracy= 0.375
Step 10, Minibatch Loss= 224.7230, Train 

In [1]:
from forward_ex_with_weight import foward_error

In [2]:
foward_error(1,[0,3,4,5,6,7],5,'1_c_ex')

W0722 22:52:58.859730 139636025993024 deprecation_wrapper.py:119] From /afs/inf.ed.ac.uk/user/s18/s1883226/Downloads/experiment/twobyt/data_gene.py:11: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.

W0722 22:52:58.890194 139636025993024 deprecation_wrapper.py:119] From /afs/inf.ed.ac.uk/user/s18/s1883226/Downloads/experiment/twobyt/convo.py:11: The name tf.nn.max_pool is deprecated. Please use tf.nn.max_pool2d instead.



4
[51456.45300375 38714.97160691 50773.03725666 38663.07606401
 64001.85620673 25909.64601132]
[5 3 1 2 0 4]
0.5767973794422177
4
[1643870.00287283 1241645.46746224 1640639.03362381 1250753.55791821
 2052776.24147537  831730.84773449]
[5 1 3 2 0 4]
0.5761627862602438
4
[51431927.88933177 38889363.96105975 51407225.09667762 38800588.12833148
 64535972.38756619 26797199.36823028]
[5 3 1 2 0 4]
0.5914141457338492
