In [1]:
from smg import generator6
generator6([20])

(array([1., 2., 3., 3., 3., 3., 3., 4., 5., 5., 5., 5., 5., 6., 7., 7., 7.,
        7., 7., 8.]), array([[0., 0., 0., 0., 0., 1., 0., 0., 0., 0.]]))

In [1]:
from smg import load_test
load_test([180])

(array([[2.80000000e+01, 2.80000000e+01, 2.80000000e+01, ...,
         2.80000000e+01, 2.80000000e+01, 2.80000000e+01],
        [2.10000000e+01, 2.20000000e+01, 2.10000000e+01, ...,
         2.20000000e+01, 2.10000000e+01, 2.20000000e+01],
        [2.70000000e+01, 2.80000000e+01, 2.90000000e+01, ...,
         2.04000000e+02, 2.05000000e+02, 2.06000000e+02],
        ...,
        [2.90000000e+01, 3.00000000e+01, 3.10000000e+01, ...,
         5.00000000e+01, 4.80000000e+01, 4.90000000e+01],
        [2.80000000e+01, 2.80000000e+01, 2.90000000e+01, ...,
         7.08459392e+36, 1.14631138e+37, 1.85477077e+37],
        [2.00000000e+01, 2.20000000e+01, 2.40000000e+01, ...,
         3.74000000e+02, 3.76000000e+02, 3.78000000e+02]]),
 array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 0.

In [1]:
from fcon_2 import train_fcon
train_fcon(2)

W0807 16:32:08.318917 140312703637312 deprecation_wrapper.py:119] From /afs/inf.ed.ac.uk/user/s18/s1883226/Downloads/experiment/test/twobyt/fcon_2.py:39: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

W0807 16:32:08.336493 140312703637312 deprecation_wrapper.py:119] From /afs/inf.ed.ac.uk/user/s18/s1883226/Downloads/experiment/test/twobyt/fcon_2.py:44: The name tf.random_normal is deprecated. Please use tf.random.normal instead.

W0807 16:32:08.391148 140312703637312 deprecation.py:506] From /afs/inf.ed.ac.uk/user/s18/s1883226/Downloads/experiment/test/twobyt/fcon_2.py:14: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
W0807 16:32:08.428787 140312703637312 deprecation.py:323] From /afs/inf.ed.ac.uk/user/s18/s1883226/Downloads/experiment/test/twobyt/fcon_2.py:66:

Step 1, Minibatch Loss= 139745.4375, Train Accuracy= 0.516
Step 100, Minibatch Loss= 2204.8042, Train Accuracy= 0.859
Step 200, Minibatch Loss= 65.2987, Train Accuracy= 0.930
Step 300, Minibatch Loss= 417.9880, Train Accuracy= 0.938


W0807 16:32:16.258001 140312703637312 deprecation.py:323] From /afs/inf.ed.ac.uk/user/s18/s1883226/miniconda3/envs/mlp/lib/python3.6/site-packages/tensorflow/python/training/saver.py:1276: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.


Step 400, Minibatch Loss= 0.0000, Train Accuracy= 1.000


array([0.69999999, 0.5       ])

In [5]:
from fcon_2 import train_fcon
import numpy as np
#ac=np.zeros((50,2))
# acc=np.zeros((50,5))
# accc=np.zeros((50,8))
# acccc=np.zeros((50,10))
for i in range (10,20):
    ac[i,:]=train_fcon(2)
    if i%5==0:
        np.save('Data/ac.npy',ac)

Step 1, Minibatch Loss= 17391.2227, Train Accuracy= 0.438
Step 100, Minibatch Loss= 64895.4805, Train Accuracy= 0.430
Step 200, Minibatch Loss= 46497.0469, Train Accuracy= 0.469
Step 300, Minibatch Loss= 2193.6074, Train Accuracy= 0.570
Step 400, Minibatch Loss= 23.8099, Train Accuracy= 0.945
Step 500, Minibatch Loss= 0.0000, Train Accuracy= 1.000
Step 1, Minibatch Loss= 85811.4688, Train Accuracy= 0.492
Step 100, Minibatch Loss= 29758.4922, Train Accuracy= 0.461
Step 200, Minibatch Loss= 8819.3223, Train Accuracy= 0.555
Step 300, Minibatch Loss= 0.0000, Train Accuracy= 1.000
Step 1, Minibatch Loss= 103432.2344, Train Accuracy= 0.539
Step 100, Minibatch Loss= 29978.4062, Train Accuracy= 0.664
Step 200, Minibatch Loss= 11136.6406, Train Accuracy= 0.758
Step 300, Minibatch Loss= 12536.4258, Train Accuracy= 0.648
Step 400, Minibatch Loss= 5424.1973, Train Accuracy= 0.703
Step 500, Minibatch Loss= 3119.7959, Train Accuracy= 0.703
Step 600, Minibatch Loss= 0.0000, Train Accuracy= 1.000
Step

In [6]:
ac

array([[0.5       , 0.5       ],
       [0.89999998, 0.89999998],
       [0.89999998, 0.89999998],
       [0.5       , 0.40000001],
       [0.40000001, 0.30000001],
       [0.5       , 0.40000001],
       [0.89999998, 0.89999998],
       [0.80000001, 0.80000001],
       [1.        , 1.        ],
       [0.5       , 0.5       ],
       [0.40000001, 0.40000001],
       [0.30000001, 0.30000001],
       [0.5       , 0.60000002],
       [0.60000002, 0.60000002],
       [0.69999999, 0.60000002],
       [0.5       , 0.5       ],
       [1.        , 1.        ],
       [0.80000001, 0.80000001],
       [0.89999998, 0.89999998],
       [0.5       , 0.5       ],
       [0.        , 0.        ],
       [0.        , 0.        ],
       [0.        , 0.        ],
       [0.        , 0.        ],
       [0.        , 0.        ],
       [0.        , 0.        ],
       [0.        , 0.        ],
       [0.        , 0.        ],
       [0.        , 0.        ],
       [0.        , 0.        ],
       [0.

In [7]:
np.average(ac[0:20,:],axis=0)

array([0.655, 0.64 ])

In [9]:
i

0

In [1]:
from fcon_2 import train_fcon
import numpy as np
#ac=np.zeros((50,2))
# acc=np.zeros((50,5))
accc=np.zeros((20,8))
# acccc=np.zeros((50,10))
for i in range (0,20):
    accc[i,:]=train_fcon(8)
    if i%5==0:
        np.save('Data/accc.npy',accc)

W0807 18:03:44.416276 140052054890304 deprecation_wrapper.py:119] From /afs/inf.ed.ac.uk/user/s18/s1883226/Downloads/experiment/test/twobyt/fcon_2.py:39: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

W0807 18:03:44.434033 140052054890304 deprecation_wrapper.py:119] From /afs/inf.ed.ac.uk/user/s18/s1883226/Downloads/experiment/test/twobyt/fcon_2.py:44: The name tf.random_normal is deprecated. Please use tf.random.normal instead.

W0807 18:03:44.474068 140052054890304 deprecation.py:506] From /afs/inf.ed.ac.uk/user/s18/s1883226/Downloads/experiment/test/twobyt/fcon_2.py:14: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
W0807 18:03:44.508157 140052054890304 deprecation.py:323] From /afs/inf.ed.ac.uk/user/s18/s1883226/Downloads/experiment/test/twobyt/fcon_2.py:66:

Step 1, Minibatch Loss= 5709615.5000, Train Accuracy= 0.133
Step 100, Minibatch Loss= 172301.5625, Train Accuracy= 0.430
Step 200, Minibatch Loss= 116536.9062, Train Accuracy= 0.578
Step 300, Minibatch Loss= 87450.1016, Train Accuracy= 0.609
Step 400, Minibatch Loss= 26140.7148, Train Accuracy= 0.742
Step 500, Minibatch Loss= 11432.9648, Train Accuracy= 0.703
Step 600, Minibatch Loss= 15998.0742, Train Accuracy= 0.766
Step 700, Minibatch Loss= 10497.8027, Train Accuracy= 0.727
Step 800, Minibatch Loss= 10927.3848, Train Accuracy= 0.695
Step 900, Minibatch Loss= 6129.2437, Train Accuracy= 0.766
Step 1000, Minibatch Loss= 4979.1992, Train Accuracy= 0.766
Step 1100, Minibatch Loss= 12323.9199, Train Accuracy= 0.711
Step 1200, Minibatch Loss= 4753.2622, Train Accuracy= 0.781
Step 1300, Minibatch Loss= 7208.1787, Train Accuracy= 0.789
Step 1400, Minibatch Loss= 3749.4124, Train Accuracy= 0.820
Step 1500, Minibatch Loss= 4719.3687, Train Accuracy= 0.812
Step 1600, Minibatch Loss= 1791.5833, 

W0807 18:05:05.031961 140052054890304 deprecation.py:323] From /afs/inf.ed.ac.uk/user/s18/s1883226/miniconda3/envs/mlp/lib/python3.6/site-packages/tensorflow/python/training/saver.py:1276: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.


Step 3000, Minibatch Loss= 260.5303, Train Accuracy= 0.883
Step 1, Minibatch Loss= 1048671.7500, Train Accuracy= 0.203
Step 100, Minibatch Loss= 143984.9531, Train Accuracy= 0.523
Step 200, Minibatch Loss= 85431.4453, Train Accuracy= 0.617
Step 300, Minibatch Loss= 75493.5625, Train Accuracy= 0.570
Step 400, Minibatch Loss= 59589.2383, Train Accuracy= 0.602
Step 500, Minibatch Loss= 23874.1211, Train Accuracy= 0.742
Step 600, Minibatch Loss= 19564.6250, Train Accuracy= 0.766
Step 700, Minibatch Loss= 27168.3848, Train Accuracy= 0.609
Step 800, Minibatch Loss= 16779.2031, Train Accuracy= 0.766
Step 900, Minibatch Loss= 13102.6494, Train Accuracy= 0.695
Step 1000, Minibatch Loss= 9289.6738, Train Accuracy= 0.641
Step 1100, Minibatch Loss= 8344.8135, Train Accuracy= 0.594
Step 1200, Minibatch Loss= 6806.7129, Train Accuracy= 0.594
Step 1300, Minibatch Loss= 3103.2297, Train Accuracy= 0.703
Step 1400, Minibatch Loss= 3716.3972, Train Accuracy= 0.773
Step 1500, Minibatch Loss= 3892.8472, Tr

Step 1300, Minibatch Loss= 1943.3396, Train Accuracy= 0.805
Step 1400, Minibatch Loss= 2184.6602, Train Accuracy= 0.820
Step 1500, Minibatch Loss= 3678.4556, Train Accuracy= 0.727
Step 1600, Minibatch Loss= 3685.2019, Train Accuracy= 0.734
Step 1700, Minibatch Loss= 2171.9651, Train Accuracy= 0.734
Step 1800, Minibatch Loss= 885.9258, Train Accuracy= 0.836
Step 1900, Minibatch Loss= 950.2587, Train Accuracy= 0.891
Step 2000, Minibatch Loss= 1105.6628, Train Accuracy= 0.812
Step 2100, Minibatch Loss= 723.7954, Train Accuracy= 0.867
Step 2200, Minibatch Loss= 682.3273, Train Accuracy= 0.836
Step 2300, Minibatch Loss= 221.2852, Train Accuracy= 0.898
Step 2400, Minibatch Loss= 231.6333, Train Accuracy= 0.852
Step 2500, Minibatch Loss= 317.1130, Train Accuracy= 0.883
Step 2600, Minibatch Loss= 140.9123, Train Accuracy= 0.844
Step 2700, Minibatch Loss= 191.5175, Train Accuracy= 0.867
Step 2800, Minibatch Loss= 240.9745, Train Accuracy= 0.836
Step 2900, Minibatch Loss= 69.2172, Train Accuracy

Step 2700, Minibatch Loss= 246.1412, Train Accuracy= 0.781
Step 2800, Minibatch Loss= 126.2048, Train Accuracy= 0.844
Step 2900, Minibatch Loss= 66.7783, Train Accuracy= 0.906
Step 3000, Minibatch Loss= 212.5807, Train Accuracy= 0.812
Step 1, Minibatch Loss= 1352821.6250, Train Accuracy= 0.227
Step 100, Minibatch Loss= 207287.8594, Train Accuracy= 0.445
Step 200, Minibatch Loss= 35820.0938, Train Accuracy= 0.820
Step 300, Minibatch Loss= 29225.6562, Train Accuracy= 0.523
Step 400, Minibatch Loss= 15118.1943, Train Accuracy= 0.750
Step 500, Minibatch Loss= 34056.5625, Train Accuracy= 0.672
Step 600, Minibatch Loss= 16620.0898, Train Accuracy= 0.633
Step 700, Minibatch Loss= 9805.5352, Train Accuracy= 0.742
Step 800, Minibatch Loss= 4529.2656, Train Accuracy= 0.781
Step 900, Minibatch Loss= 11708.4336, Train Accuracy= 0.758
Step 1000, Minibatch Loss= 4398.2529, Train Accuracy= 0.734
Step 1100, Minibatch Loss= 5433.2510, Train Accuracy= 0.727
Step 1200, Minibatch Loss= 2669.1809, Train Ac

Step 1000, Minibatch Loss= 7136.9707, Train Accuracy= 0.734
Step 1100, Minibatch Loss= 8876.8125, Train Accuracy= 0.812
Step 1200, Minibatch Loss= 6734.3311, Train Accuracy= 0.781
Step 1300, Minibatch Loss= 2394.2678, Train Accuracy= 0.836
Step 1400, Minibatch Loss= 3943.8726, Train Accuracy= 0.789
Step 1500, Minibatch Loss= 3876.7427, Train Accuracy= 0.836
Step 1600, Minibatch Loss= 3537.9016, Train Accuracy= 0.797
Step 1700, Minibatch Loss= 3548.0486, Train Accuracy= 0.812
Step 1800, Minibatch Loss= 1518.0386, Train Accuracy= 0.852
Step 1900, Minibatch Loss= 1390.2645, Train Accuracy= 0.836
Step 2000, Minibatch Loss= 1433.4532, Train Accuracy= 0.828
Step 2100, Minibatch Loss= 1017.9874, Train Accuracy= 0.797
Step 2200, Minibatch Loss= 925.8620, Train Accuracy= 0.828
Step 2300, Minibatch Loss= 832.5416, Train Accuracy= 0.859
Step 2400, Minibatch Loss= 416.5442, Train Accuracy= 0.883
Step 2500, Minibatch Loss= 163.3933, Train Accuracy= 0.898
Step 2600, Minibatch Loss= 231.6565, Train A

Step 2400, Minibatch Loss= 325.3745, Train Accuracy= 0.914
Step 2500, Minibatch Loss= 465.4109, Train Accuracy= 0.859
Step 2600, Minibatch Loss= 399.1396, Train Accuracy= 0.812
Step 2700, Minibatch Loss= 367.4223, Train Accuracy= 0.844
Step 2800, Minibatch Loss= 240.8935, Train Accuracy= 0.852
Step 2900, Minibatch Loss= 154.7968, Train Accuracy= 0.883
Step 3000, Minibatch Loss= 199.2607, Train Accuracy= 0.891
Step 1, Minibatch Loss= 3126892.5000, Train Accuracy= 0.125
Step 100, Minibatch Loss= 110386.4609, Train Accuracy= 0.523
Step 200, Minibatch Loss= 87999.9219, Train Accuracy= 0.570
Step 300, Minibatch Loss= 24228.4414, Train Accuracy= 0.555
Step 400, Minibatch Loss= 18196.3516, Train Accuracy= 0.672
Step 500, Minibatch Loss= 22140.7598, Train Accuracy= 0.688
Step 600, Minibatch Loss= 16281.3594, Train Accuracy= 0.648
Step 700, Minibatch Loss= 12416.1611, Train Accuracy= 0.688
Step 800, Minibatch Loss= 8429.9785, Train Accuracy= 0.719
Step 900, Minibatch Loss= 6790.1143, Train Accu

KeyboardInterrupt: 

In [3]:
accc

array([[0.80000001, 0.69999999, 0.69999999, 0.69999999, 0.69999999,
        0.69999999, 0.69999999, 0.69999999],
       [0.80000001, 0.69999999, 0.80000001, 0.80000001, 0.69999999,
        0.80000001, 0.80000001, 0.69999999],
       [0.69999999, 0.69999999, 0.69999999, 0.69999999, 0.69999999,
        0.69999999, 0.69999999, 0.69999999],
       [0.80000001, 0.80000001, 0.80000001, 0.80000001, 0.69999999,
        0.80000001, 0.69999999, 0.69999999],
       [0.69999999, 0.69999999, 0.69999999, 0.69999999, 0.69999999,
        0.69999999, 0.69999999, 0.69999999],
       [0.69999999, 0.80000001, 0.69999999, 0.80000001, 0.69999999,
        0.69999999, 0.69999999, 0.80000001],
       [0.80000001, 0.69999999, 0.69999999, 0.80000001, 0.80000001,
        0.69999999, 0.80000001, 0.69999999],
       [0.80000001, 0.80000001, 0.89999998, 0.80000001, 0.89999998,
        0.80000001, 0.80000001, 0.80000001],
       [0.69999999, 0.80000001, 0.69999999, 0.69999999, 0.69999999,
        0.69999999, 0.699999

In [2]:
from tensorpack.train.config import TrainConfig

In [4]:
import numpy as np
np.array([0., 0., 1., 1., 0., 0., 0., 0.]).shape

(8,)

In [5]:
an=np.zeros((50,8))
an[0,:]=np.array([0., 0., 1., 1., 0., 0., 0., 0.])