In [7]:
import numpy as np
ac=np.load('Data/ac.npy')
np.average(ac[0:15,:],axis=0)

array([0.62666667, 0.60666667])

In [19]:
import numpy as np
acc=np.load('Data/acc.npy')
np.average(acc[0:15,:],axis=0)


array([0.56666668, 0.56666668, 0.56666668, 0.59333335, 0.58000001])

In [14]:
import numpy as np
accc=np.load('Data/accc.npy')
np.average(accc[0:15,:],axis=0)

array([0.76666667, 0.74666667, 0.77999999, 0.77333333, 0.75333333,
       0.72666667, 0.73333333, 0.75333333])

In [20]:
import numpy as np
accc=np.load('Data/accc_2d.npy')
np.average(accc[0:15,:],axis=0)

array([0.74000001, 0.73333334, 0.76666667, 0.74      , 0.75333334,
       0.75333334, 0.72666667, 0.76000001])

In [13]:
import numpy as np
acccc=np.load('Data/acccc.npy')
np.average(acccc[0:15,:],axis=0)

array([0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1])

In [2]:
import numpy as np
accc=np.load('Data/accc_3d.npy')
np.average(accc[0:15,:],axis=0)
accc

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [3]:
from fcon_2 import train_fcon
import numpy as np
#ac=np.zeros((50,2))
#acc=np.zeros((50,5))
accc=train_fcon(8)


W0808 17:27:49.801585 140418846426944 deprecation_wrapper.py:119] From /afs/inf.ed.ac.uk/user/s18/s1883226/Downloads/experiment/test/twobyt/fcon_2.py:39: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

W0808 17:27:50.016940 140418846426944 deprecation_wrapper.py:119] From /afs/inf.ed.ac.uk/user/s18/s1883226/Downloads/experiment/test/twobyt/fcon_2.py:44: The name tf.random_normal is deprecated. Please use tf.random.normal instead.

W0808 17:27:50.066511 140418846426944 deprecation.py:506] From /afs/inf.ed.ac.uk/user/s18/s1883226/Downloads/experiment/test/twobyt/fcon_2.py:14: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
W0808 17:27:50.098591 140418846426944 deprecation.py:323] From /afs/inf.ed.ac.uk/user/s18/s1883226/Downloads/experiment/test/twobyt/fcon_2.py:66:

Step 1, Minibatch Loss= 1230801.2500, Train Accuracy= 0.117
Step 100, Minibatch Loss= 33763.2266, Train Accuracy= 0.609
Step 200, Minibatch Loss= 11304.1318, Train Accuracy= 0.672
Step 300, Minibatch Loss= 8919.3135, Train Accuracy= 0.688
Step 400, Minibatch Loss= 4698.9585, Train Accuracy= 0.734
Step 500, Minibatch Loss= 1489.1028, Train Accuracy= 0.781
Step 600, Minibatch Loss= 1023.6887, Train Accuracy= 0.852
Step 700, Minibatch Loss= 1056.8606, Train Accuracy= 0.852
Step 800, Minibatch Loss= 1789.9080, Train Accuracy= 0.859
Step 900, Minibatch Loss= 886.6132, Train Accuracy= 0.859
Step 1000, Minibatch Loss= 1278.6527, Train Accuracy= 0.883
Step 1100, Minibatch Loss= 195.8220, Train Accuracy= 0.922
Step 1200, Minibatch Loss= 360.4207, Train Accuracy= 0.938
Step 1300, Minibatch Loss= 1063.3511, Train Accuracy= 0.836
Step 1400, Minibatch Loss= 356.1243, Train Accuracy= 0.867
Step 1500, Minibatch Loss= 455.9652, Train Accuracy= 0.859
Step 1600, Minibatch Loss= 721.8402, Train Accuracy=

W0808 17:32:09.179174 140418846426944 deprecation.py:323] From /afs/inf.ed.ac.uk/user/s18/s1883226/miniconda3/envs/mlp/lib/python3.6/site-packages/tensorflow/python/training/saver.py:1276: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.


Step 3000, Minibatch Loss= 12.6399, Train Accuracy= 0.906


In [3]:
import numpy as np
accc=np.load('Data/acc_3d.npy')
np.average(accc[0:15,:],axis=0)


array([0.61333334, 0.62666667, 0.61333334, 0.64666667, 0.63333334])

In [1]:
import numpy as np
accc=np.load('Data/acc_2d_1.npy')
np.average(accc[0:15,:],axis=0)

array([0.65333333, 0.64666667, 0.64      , 0.64      , 0.64000001])

In [2]:
import numpy as np
accc=np.load('Data/ac_2d_1.npy')
np.average(accc[0:15,:],axis=0)

array([0.74666667, 0.74      ])

In [7]:
import numpy as np
accc=np.load('Data/accc_2d_1.npy')
np.average(accc[0:15,:],axis=0)

array([0.76666667, 0.76666667, 0.76000001, 0.76666667, 0.76666667,
       0.73333333, 0.76      , 0.77333334])

In [6]:
import numpy as np
accc=np.load('Data/accc_t2.npy')
np.average(accc[0:15,:],axis=0)


array([0.23333334, 0.23333334, 0.23333334, 0.23333334, 0.23333334,
       0.23333334, 0.23333334, 0.23333334])

In [1]:
import numpy as np
accc=np.load('Data/acccc_2d.npy')
np.average(accc[0:15,:],axis=0)
accc

array([[0.89999998, 0.89999998, 0.89999998, 0.89999998, 0.89999998,
        0.89999998, 0.89999998, 0.89999998, 0.89999998, 0.89999998],
       [0.89999998, 0.89999998, 0.89999998, 0.89999998, 0.89999998,
        0.89999998, 0.89999998, 0.89999998, 0.89999998, 0.89999998],
       [0.89999998, 0.89999998, 0.89999998, 0.89999998, 0.89999998,
        0.89999998, 0.89999998, 0.89999998, 0.89999998, 0.89999998],
       [0.89999998, 0.89999998, 0.89999998, 0.89999998, 0.89999998,
        0.89999998, 0.89999998, 0.89999998, 0.89999998, 0.89999998],
       [0.89999998, 0.89999998, 1.        , 0.89999998, 0.89999998,
        0.89999998, 0.89999998, 0.89999998, 1.        , 1.        ],
       [0.89999998, 0.89999998, 1.        , 0.89999998, 0.89999998,
        0.89999998, 0.89999998, 0.89999998, 0.89999998, 1.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.       