In [15]:
import numpy as np
N='98'
ans=3
EEE=np.load('Data/'+N+str('EEE_rnn')+'.npy')
NN=np.load('Data/'+N+str('NN_rnn')+'.npy')
ac=np.load('Data/'+N+str('ac_rnn')+'.npy')
print(np.argsort(np.average(EEE,axis=1)))
print(np.where(NN==ans)[0].size)
print(np.average(EEE,axis=1)[ans]/EEE.mean())
print(ac.mean())

[5 2 3 1 0 4]
8
0.9574440487473109
0.7400000000000001


In [16]:
import numpy as np
N='82'
ans=2
EEE=np.load('Data/'+N+str('EEE_rnn_1')+'.npy')
NN=np.load('Data/'+N+str('NN_rnn_1')+'.npy')
ac=np.load('Data/'+N+str('ac_rnn_1')+'.npy')
print(np.argsort(np.average(EEE,axis=1)))
print(np.where(NN==ans)[0].size)
print(np.average(EEE,axis=1)[ans]/EEE.mean())
print(ac.mean())

[0 2 3 4 1 5]
6
0.8711623410453345
0.3416666666666666


In [8]:
import numpy as np
N='43'
ans=5
EEE=np.load('Data/'+N+str('EEE_rnn_1')+'.npy')
NN=np.load('Data/'+N+str('NN_rnn_1')+'.npy')
ac=np.load('Data/'+N+str('ac_rnn_1')+'.npy')
print(np.argsort(np.average(EEE,axis=1)))
print(np.where(NN==ans)[0].size)
print(np.average(EEE,axis=1)[ans]/EEE.mean())
print(ac.mean())

FileNotFoundError: [Errno 2] No such file or directory: 'Data/43EEE_rnn_1.npy'

In [4]:
import numpy as np
N=''
ans=0
EEE=np.load('Data/'+N+str('EEE_rnn')+'.npy')
NN=np.load('Data/'+N+str('NN_rnn')+'.npy')
ac=np.load('Data/'+N+str('ac_rnn')+'.npy')
print(np.argsort(np.average(EEE,axis=1)))
print(np.where(NN==ans)[0].size)
print(np.average(EEE,axis=1)[ans]/EEE.mean())
print(ac.mean())

[2 1 5 3 4 0]
2
1.105157179051692
0.6300000000000001
