In [1]:
from rcon import train_rcon

In [1]:
from run_r_error import foward_error

In [2]:
foward_error(1,[0,3,4,5,6,7],5,'1_c_r')

W0726 18:54:44.520908 140494694561600 deprecation_wrapper.py:119] From /afs/inf.ed.ac.uk/user/s18/s1883226/Downloads/experiment/twobyt/con1.py:21: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

W0726 18:54:44.525789 140494694561600 deprecation_wrapper.py:119] From /afs/inf.ed.ac.uk/user/s18/s1883226/Downloads/experiment/twobyt/con1.py:27: The name tf.random_normal is deprecated. Please use tf.random.normal instead.

W0726 18:54:44.584973 140494694561600 deprecation_wrapper.py:119] From /afs/inf.ed.ac.uk/user/s18/s1883226/Downloads/experiment/twobyt/convo.py:11: The name tf.nn.max_pool is deprecated. Please use tf.nn.max_pool2d instead.

W0726 18:54:44.593084 140494694561600 deprecation.py:506] From /afs/inf.ed.ac.uk/user/s18/s1883226/Downloads/experiment/twobyt/convo.py:38: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of

Step 1, Minibatch Loss= 6529.2295, Train Accuracy= 0.000
Step 2, Minibatch Loss= 0.0000, Train Accuracy= 1.000
Step 3, Minibatch Loss= 7157.7896, Train Accuracy= 0.000
Step 4, Minibatch Loss= 0.0000, Train Accuracy= 1.000
Step 5, Minibatch Loss= 10591.7539, Train Accuracy= 0.000
Step 6, Minibatch Loss= 10597.6514, Train Accuracy= 0.000
Step 7, Minibatch Loss= 24348.3203, Train Accuracy= 0.000
Step 8, Minibatch Loss= 7357.5405, Train Accuracy= 0.000
Step 9, Minibatch Loss= 482.5039, Train Accuracy= 0.000
Step 10, Minibatch Loss= 3545.5610, Train Accuracy= 0.000
Step 11, Minibatch Loss= 3930.2725, Train Accuracy= 0.000
Step 12, Minibatch Loss= 0.0000, Train Accuracy= 1.000


W0726 18:54:45.666388 140494694561600 deprecation_wrapper.py:119] From /afs/inf.ed.ac.uk/user/s18/s1883226/Downloads/experiment/twobyt/rcon.py:29: The name tf.reset_default_graph is deprecated. Please use tf.compat.v1.reset_default_graph instead.

W0726 18:54:45.680580 140494694561600 deprecation.py:323] From /afs/inf.ed.ac.uk/user/s18/s1883226/Downloads/experiment/twobyt/rcon.py:20: BasicLSTMCell.__init__ (from tensorflow.python.ops.rnn_cell_impl) is deprecated and will be removed in a future version.
Instructions for updating:
This class is equivalent as tf.keras.layers.LSTMCell, and will be replaced by that in Tensorflow 2.0.
W0726 18:54:45.681716 140494694561600 deprecation.py:323] From /afs/inf.ed.ac.uk/user/s18/s1883226/Downloads/experiment/twobyt/rcon.py:23: static_rnn (from tensorflow.python.ops.rnn) is deprecated and will be removed in a future version.
Instructions for updating:
Please use `keras.layers.RNN(cell, unroll=True)`, which is equivalent to this API
W0726 18:54:45.7

Step 1, Minibatch Loss= 17849.6367, Train Accuracy= 0.000
Step 2, Minibatch Loss= 3871.6641, Train Accuracy= 0.000
Step 3, Minibatch Loss= 0.0000, Train Accuracy= 1.000
Step 4, Minibatch Loss= 62286.5859, Train Accuracy= 0.000
Step 5, Minibatch Loss= 17569.7168, Train Accuracy= 0.000
Step 6, Minibatch Loss= 47515.8828, Train Accuracy= 0.000
Step 7, Minibatch Loss= 0.0000, Train Accuracy= 1.000


W0726 18:54:46.041278 140494694561600 deprecation_wrapper.py:119] From /afs/inf.ed.ac.uk/user/s18/s1883226/Downloads/experiment/twobyt/rcon.py:72: The name tf.train.GradientDescentOptimizer is deprecated. Please use tf.compat.v1.train.GradientDescentOptimizer instead.



Step 1, Minibatch Loss= 5.6834, Train Accuracy= 0.625
Step 2, Minibatch Loss= 4.0384, Train Accuracy= 0.625
Step 3, Minibatch Loss= 3.4279, Train Accuracy= 0.250
Step 4, Minibatch Loss= 0.3141, Train Accuracy= 1.000
Step 5, Minibatch Loss= 0.3896, Train Accuracy= 0.875
Step 6, Minibatch Loss= 0.2201, Train Accuracy= 1.000
Step 1, Minibatch Loss= 1.1545, Train Accuracy= 0.375
Step 2, Minibatch Loss= 1.0746, Train Accuracy= 0.500
Step 3, Minibatch Loss= 0.5496, Train Accuracy= 1.000
Step 4, Minibatch Loss= 0.5104, Train Accuracy= 1.000
Step 5, Minibatch Loss= 0.4610, Train Accuracy= 1.000
Step 6, Minibatch Loss= 0.3634, Train Accuracy= 1.000
[5 3 2 1 0 4]
0.21439373332650216
2


In [6]:
import numpy as np
a=np.zeros((4,4))

In [8]:
a[:,0:2]

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [5]:
import numpy as np
N_str='1_c_r'
EE=np.load('Data/'+str(N_str)+'Error.npy')

In [6]:
EE

array([[3.41381049],
       [2.27857733],
       [4.44455576],
       [1.15925312],
       [1.60208845],
       [1.13494968]])