In [1]:
from forward_error_with_weight import foward_error

In [2]:
foward_error(1,[0,3,4,5,6,7],5,'1_c_3')

W0715 18:21:51.379550 139781223868224 deprecation_wrapper.py:119] From /afs/inf.ed.ac.uk/user/s18/s1883226/Downloads/experiment/twobyt/data_gene.py:11: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.

W0715 18:21:51.414754 139781223868224 deprecation_wrapper.py:119] From /afs/inf.ed.ac.uk/user/s18/s1883226/Downloads/experiment/twobyt/convo.py:11: The name tf.nn.max_pool is deprecated. Please use tf.nn.max_pool2d instead.



50
[55051.68825247 51453.08613254 56732.50354495 50215.44314855
 67597.05881929 27618.29038693]
[5 3 1 0 2 4]
0.5368541753241081
50
[ 882945.12251367  819317.28276389  902364.82111005  798533.50282435
 1074840.93641756  440865.99173511]
[5 3 1 0 2 4]
0.537765220507655
50
[ 9927692.06470975  9264367.40691116 10233325.77168389  9033646.21173859
 12164976.68967163  4973406.97750406]
[5 3 1 0 2 4]
0.5367235472984941


In [3]:
foward_error(2,[0,1,5,6,7,8],0,'2_c_3')

50
[ 31734.46985061 120493.04713984 100182.27813955 110865.93250507
 100344.52568479  99528.60084302]
[0 5 2 4 3 1]
0.33811099444867165
50
[ 511974.14142281 1928391.85618321 1600251.66796109 1769719.63761637
 1599113.30326086 1587554.80831219]
[0 5 4 2 3 1]
0.34142969876382673
50
[ 5892605.01344502 21657687.72433834 17831821.23121755 19669962.19555976
 17816911.52978507 17654580.39377986]
[0 5 4 2 3 1]
0.35171483417376354


In [4]:
foward_error(3,[0,1,5,6,7,8],1,'3_c_3')

0
[ 98707.58734077  99783.74999843  84025.69612803  60930.71938977
 122977.09599256  87227.52331847]
[3 2 5 0 1 4]
1.0813689782383828
0
[1604575.66423791 1560574.11699952 1384332.89694081  964442.16622428
 1909362.21364605 1419251.00775226]
[3 2 5 1 0 4]
1.0589091765644691
0
[18317564.16217076 17408517.5900976  15412839.80000252 10715432.00245539
 21966968.83697577 16024445.21050827]
[3 2 5 1 0 4]
1.046124518334349


In [5]:
foward_error(4,[0,1,2,3,5,8],0,'4_c_3')

0
[ 87979.11425224  74631.21615446  96587.10631515 110375.22590989
  71631.12167179 103086.41591436]
[4 1 0 2 5 3]
0.9698405102684596
0
[1395277.15665619 1185555.55196639 1539594.51380622 1762747.76748418
 1145750.15452866 1649292.46754338]
[4 1 0 2 5 3]
0.9646753877634353
0
[15671031.1189981  13399378.92960699 17493385.12660797 19927009.76434723
 13016100.4467015  18640707.03810881]
[4 1 0 2 5 3]
0.958007886197356
